CREATE TABLE plans (
 id text PRIMARY KEY, name text NOT NULL, active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now()
);
-- statement
CREATE TABLE plan_versions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id text NOT NULL REFERENCES plans(id),
 version integer NOT NULL CHECK(version > 0), price_minor_units integer NOT NULL CHECK(price_minor_units >= 0),
 currency text NOT NULL CHECK(currency = 'TRY'), monthly_quota integer NOT NULL CHECK(monthly_quota > 0),
 background_tier text NOT NULL CHECK(background_tier IN ('basic','full')),
 trial_period_days integer NOT NULL DEFAULT 0 CHECK(trial_period_days BETWEEN 0 AND 7),
 iyzico_product_reference_code text, iyzico_pricing_plan_reference_code text UNIQUE,
 iyzico_trial_plan_reference_code text UNIQUE,
 published_at timestamptz, retired_at timestamptz, UNIQUE(plan_id,version),
 CHECK(price_minor_units = 0 OR published_at IS NULL OR (iyzico_product_reference_code IS NOT NULL AND iyzico_pricing_plan_reference_code IS NOT NULL)),
 CHECK(trial_period_days = 0 OR iyzico_trial_plan_reference_code IS NOT NULL),
 CHECK(price_minor_units > 0 OR trial_period_days = 0)
);
-- statement
CREATE UNIQUE INDEX plan_versions_live ON plan_versions(plan_id) WHERE published_at IS NOT NULL AND retired_at IS NULL;
-- statement
CREATE TABLE subscriptions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
 provider text CHECK(provider = 'iyzico'), provider_subscription_reference text UNIQUE,
 status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','trialing','past_due','canceling','canceled','suspended','expired')),
 access_until timestamptz, trial_used_at timestamptz, renewal_check_after timestamptz,
 deletion_requested_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
-- statement
CREATE TABLE subscription_periods (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subscription_id uuid NOT NULL REFERENCES subscriptions(id),
 user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, plan_version_id uuid NOT NULL REFERENCES plan_versions(id),
 provider_subscription_reference text, provider_order_reference text UNIQUE,
 starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL CHECK(ends_at > starts_at),
 quota_snapshot integer NOT NULL CHECK(quota_snapshot > 0), used_this_period integer NOT NULL DEFAULT 0 CHECK(used_this_period >= 0 AND used_this_period <= quota_snapshot),
 status text NOT NULL DEFAULT 'active' CHECK(status IN ('pending','active','superseded','expired','suspended')),
 created_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz
);
-- statement
CREATE UNIQUE INDEX subscription_periods_active ON subscription_periods(subscription_id) WHERE status = 'active';
-- statement
CREATE INDEX subscription_periods_owner ON subscription_periods(user_id, starts_at DESC);
-- statement
CREATE TABLE usage_reservations (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), period_id uuid NOT NULL REFERENCES subscription_periods(id),
 user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, request_id uuid NOT NULL,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','consumed','released')),
 created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz,
 UNIQUE(user_id,request_id)
);
-- statement
CREATE INDEX usage_reservations_pending ON usage_reservations(created_at) WHERE status = 'pending';
-- statement
CREATE TABLE usage_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, period_id uuid NOT NULL REFERENCES subscription_periods(id),
 reservation_id uuid NOT NULL UNIQUE REFERENCES usage_reservations(id), user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
 event_type text NOT NULL DEFAULT 'background_removal', created_at timestamptz NOT NULL DEFAULT now()
);
-- statement
CREATE TABLE checkout_sessions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
 plan_version_id uuid NOT NULL REFERENCES plan_versions(id), idempotency_key uuid NOT NULL,
 customer_reference_code text, conversation_reference uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
 expected_amount_minor_units integer NOT NULL CHECK(expected_amount_minor_units > 0), currency text NOT NULL CHECK(currency = 'TRY'),
 pricing_plan_reference text NOT NULL, provider_checkout_token text UNIQUE, provider_subscription_reference text UNIQUE,
 checkout_form_content text, trial_status text NOT NULL DEFAULT 'none' CHECK(trial_status IN ('none','reserved','consumed','released')),
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','completed','expired','failed')),
 initialization_started boolean NOT NULL DEFAULT false,
 next_verification_at timestamptz NOT NULL DEFAULT now(),
 created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL DEFAULT now() + interval '30 minutes', completed_at timestamptz,
 UNIQUE(user_id,idempotency_key)
);
-- statement
CREATE UNIQUE INDEX checkout_one_pending ON checkout_sessions(user_id) WHERE status = 'pending';
-- statement
CREATE UNIQUE INDEX checkout_one_trial ON checkout_sessions(user_id) WHERE trial_status = 'reserved' AND status = 'pending';
-- statement
CREATE TABLE billing_transactions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
 retention_subject uuid NOT NULL DEFAULT gen_random_uuid(), period_id uuid REFERENCES subscription_periods(id),
 type text NOT NULL CHECK(type IN ('charge','refund','chargeback','chargeback_reversal')),
 status text NOT NULL CHECK(status IN ('succeeded','failed','disputed','won','lost')),
 amount_minor_units integer NOT NULL CHECK(amount_minor_units >= 0), currency text NOT NULL CHECK(currency = 'TRY'),
 provider text NOT NULL DEFAULT 'iyzico', provider_transaction_reference text NOT NULL,
 provider_payment_id text, original_transaction_id uuid REFERENCES billing_transactions(id),
 invoice_reference text, created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(provider,provider_transaction_reference,type)
);
-- statement
CREATE INDEX billing_transactions_owner ON billing_transactions(user_id,created_at DESC,id);
-- statement
CREATE TABLE webhook_events (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider text NOT NULL DEFAULT 'iyzico', provider_event_id text NOT NULL,
 event_type text NOT NULL, payload jsonb NOT NULL, processed_at timestamptz,
 processing_attempts integer NOT NULL DEFAULT 0, last_error text, lease_until timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider,provider_event_id)
);
-- statement
CREATE TABLE provider_actions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
 kind text NOT NULL CHECK(kind IN ('cancel_subscription','refund_payment','suspend_entitlement','delete_account')),
 idempotency_key text NOT NULL UNIQUE, target_reference text NOT NULL, payload jsonb NOT NULL DEFAULT '{}',
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','succeeded','failed','uncertain')),
 attempts integer NOT NULL DEFAULT 0, last_error text, lease_until timestamptz,
 dispatched_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
);
-- statement
CREATE TABLE storage_deletion_jobs (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid UNIQUE REFERENCES projects(id) ON DELETE SET NULL,
 r2_key text NOT NULL, thumbnail_r2_key text NOT NULL, reason text NOT NULL,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','succeeded','failed')),
 attempts integer NOT NULL DEFAULT 0, last_error text, lease_until timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
-- statement
CREATE TABLE billing_alerts (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), deduplication_key text NOT NULL UNIQUE,
 kind text NOT NULL, reference text NOT NULL, detail text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz
);
-- statement
CREATE TABLE billing_runs (name text PRIMARY KEY, last_started_at timestamptz, last_succeeded_at timestamptz, last_error text);
-- statement
ALTER TABLE backgrounds ADD COLUMN tier text NOT NULL DEFAULT 'basic' CHECK(tier IN ('basic','full'));
-- statement
ALTER TABLE projects ADD COLUMN background_id uuid REFERENCES backgrounds(id);
-- statement
ALTER TABLE user_consents DROP CONSTRAINT user_consents_document_type;
-- statement
ALTER TABLE user_consents ADD CONSTRAINT user_consents_document_type CHECK(document_type IN ('terms','kvkk_notice','distance_sales','pre_information'));
-- statement
ALTER TABLE user_consents DROP CONSTRAINT user_consents_user_document_version_key;
-- statement
ALTER TABLE user_consents DROP CONSTRAINT user_consents_user_id_fkey;
-- statement
ALTER TABLE user_consents ALTER COLUMN user_id DROP NOT NULL;
-- statement
ALTER TABLE user_consents ADD FOREIGN KEY(user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
-- statement
ALTER TABLE user_consents ADD COLUMN document_hash text, ADD COLUMN locale text,
 ADD COLUMN plan_version_id uuid REFERENCES plan_versions(id), ADD COLUMN checkout_session_id uuid REFERENCES checkout_sessions(id),
 ADD COLUMN retention_subject uuid NOT NULL DEFAULT gen_random_uuid();
-- statement
CREATE UNIQUE INDEX user_consents_signup_unique ON user_consents(user_id,document_type,document_version) WHERE checkout_session_id IS NULL;
-- statement
CREATE UNIQUE INDEX user_consents_checkout_unique ON user_consents(user_id,document_type,document_version,checkout_session_id) WHERE checkout_session_id IS NOT NULL;
-- statement
CREATE OR REPLACE FUNCTION public.record_signup_consents() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE accepted_version text;
BEGIN
 accepted_version := nullif(new.raw_user_meta_data ->> 'terms_version','');
 IF accepted_version IS NULL OR new.raw_user_meta_data ->> 'terms_accepted' IS DISTINCT FROM 'true' THEN RETURN new; END IF;
 INSERT INTO public.user_consents(user_id,document_type,document_version)
 VALUES(new.id,'terms',accepted_version),(new.id,'kvkk_notice',accepted_version)
 ON CONFLICT(user_id,document_type,document_version) WHERE checkout_session_id IS NULL DO NOTHING;
 RETURN new;
END $$;
-- statement
INSERT INTO plans(id,name) VALUES ('deneme','Deneme'),('atolye','Atölye'),('magaza','Mağaza');
-- statement
INSERT INTO plan_versions(plan_id,version,price_minor_units,currency,monthly_quota,background_tier,published_at)
 VALUES('deneme',1,0,'TRY',10,'basic',now());
-- statement
CREATE FUNCTION public.billing_signup() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE sid uuid; pv public.plan_versions;
BEGIN
 SELECT * INTO STRICT pv FROM public.plan_versions WHERE plan_id='deneme' AND published_at IS NOT NULL AND retired_at IS NULL;
 INSERT INTO public.subscriptions(user_id,access_until) VALUES(new.id,now()+interval '1 month') RETURNING id INTO sid;
 INSERT INTO public.subscription_periods(subscription_id,user_id,plan_version_id,starts_at,ends_at,quota_snapshot)
 VALUES(sid,new.id,pv.id,now(),now()+interval '1 month',pv.monthly_quota);
 RETURN new;
END $$;
-- statement
CREATE TRIGGER billing_signup AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.billing_signup();
-- statement
INSERT INTO subscriptions(user_id,access_until) SELECT id,now()+interval '1 month' FROM auth.users ON CONFLICT(user_id) DO NOTHING;
-- statement
INSERT INTO subscription_periods(subscription_id,user_id,plan_version_id,starts_at,ends_at,quota_snapshot)
 SELECT s.id,s.user_id,v.id,now(),now()+interval '1 month',v.monthly_quota FROM subscriptions s CROSS JOIN plan_versions v WHERE v.plan_id='deneme';
-- statement
CREATE FUNCTION public.billing_delete_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM public.subscriptions WHERE user_id=old.id AND provider_subscription_reference IS NOT NULL AND status NOT IN ('canceled','expired'))
 OR EXISTS(SELECT 1 FROM public.checkout_sessions WHERE user_id=old.id AND status='pending')
 OR EXISTS(SELECT 1 FROM public.provider_actions WHERE user_id=old.id AND kind IN ('cancel_subscription','refund_payment') AND status<>'succeeded') THEN
 RAISE EXCEPTION 'billing cancellation must complete before account deletion';
 END IF;
 RETURN old;
END $$;
-- statement
CREATE TRIGGER billing_delete_guard BEFORE DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.billing_delete_guard();
-- statement
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['plans','plan_versions','subscriptions','subscription_periods','usage_reservations','usage_events','checkout_sessions','billing_transactions','webhook_events','provider_actions','storage_deletion_jobs','billing_alerts','billing_runs'] LOOP
 EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated',t);
 END LOOP;
 REVOKE ALL ON SEQUENCE public.usage_events_id_seq FROM anon, authenticated;
 REVOKE ALL ON FUNCTION public.billing_signup() FROM PUBLIC, anon, authenticated;
 REVOKE ALL ON FUNCTION public.billing_delete_guard() FROM PUBLIC, anon, authenticated;
END $$;
-- statement
CREATE FUNCTION public.billing_immutable_snapshot() RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN
 IF TG_TABLE_NAME='plan_versions' THEN
  IF (to_jsonb(new)-'retired_at') IS DISTINCT FROM (to_jsonb(old)-'retired_at') THEN RAISE EXCEPTION 'plan version is immutable'; END IF;
 ELSIF TG_TABLE_NAME='billing_transactions' THEN
  IF (to_jsonb(new)-'user_id'-'invoice_reference') IS DISTINCT FROM (to_jsonb(old)-'user_id'-'invoice_reference')
   OR (new.user_id IS DISTINCT FROM old.user_id AND new.user_id IS NOT NULL)
   OR (old.invoice_reference IS NOT NULL AND new.invoice_reference IS DISTINCT FROM old.invoice_reference)
  THEN RAISE EXCEPTION 'financial transaction is immutable'; END IF;
 ELSIF TG_TABLE_NAME='user_consents' THEN
  IF (to_jsonb(new)-'user_id') IS DISTINCT FROM (to_jsonb(old)-'user_id')
   OR (new.user_id IS DISTINCT FROM old.user_id AND new.user_id IS NOT NULL)
  THEN RAISE EXCEPTION 'consent is immutable'; END IF;
 END IF;
 RETURN new;
END $$;
-- statement
CREATE TRIGGER plan_version_snapshot BEFORE UPDATE ON plan_versions FOR EACH ROW EXECUTE FUNCTION public.billing_immutable_snapshot();
-- statement
CREATE TRIGGER financial_snapshot BEFORE UPDATE ON billing_transactions FOR EACH ROW EXECUTE FUNCTION public.billing_immutable_snapshot();
-- statement
CREATE TRIGGER consent_snapshot BEFORE UPDATE ON user_consents FOR EACH ROW EXECUTE FUNCTION public.billing_immutable_snapshot();
-- statement
REVOKE ALL ON FUNCTION public.billing_immutable_snapshot() FROM PUBLIC,anon,authenticated;
