-- Faz 6 admin paneli: bonus krediler, denetim günlüğü ve rezervasyonun kredi kaynağı.
--
-- BONUS KREDİ NEDEN AYRI TABLO: `subscription_periods.quota_snapshot` 0006'daki
-- `period_snapshot` trigger'ıyla DEĞİŞMEZ — dönem bir kanıt kaydı ve öyle kalmalı.
-- Admin'in verdiği kredi dönemin kotasını büyütmez; kendi tablosunda durur ve
-- dönem kotası tükendiğinde tüketilir.
CREATE TABLE credit_grants (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 -- Hesap silinince kimlik kopar ama kayıt kalır (`billing_transactions` deseni).
 user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
 retention_subject uuid NOT NULL DEFAULT gen_random_uuid(),
 amount integer NOT NULL CHECK(amount > 0 AND amount <= 10000),
 used integer NOT NULL DEFAULT 0 CHECK(used >= 0 AND used <= amount),
 reason text NOT NULL CHECK(length(reason) BETWEEN 3 AND 500),
 granted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
 -- Kimlik İŞİ tanımlar, isteği değil: aynı anahtarla gelen ikinci istek ikinci
 -- krediyi AÇMAZ (kök CLAUDE.md ders 24).
 idempotency_key text NOT NULL UNIQUE,
 expires_at timestamptz, revoked_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now()
);
-- statement
CREATE INDEX credit_grants_available ON credit_grants(user_id, expires_at, created_at)
 WHERE revoked_at IS NULL;
-- statement
-- Rezervasyon krediyi hangi kovadan aldı: bu sütun olmadan başarısız bir iş
-- krediyi YANLIŞ kovaya iade ederdi (grant'ten alınan kredi dönemin sayacını
-- eksiye çekerdi).
ALTER TABLE usage_reservations ADD COLUMN grant_id uuid REFERENCES credit_grants(id);
-- statement
-- Admin eylemlerinin izi. `actor_id` bilinçli olarak FK DEĞİL: yöneticinin
-- hesabı silinse bile denetim satırı kime ait olduğunu söylemeye devam etmeli.
CREATE TABLE admin_audit_log (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 actor_id uuid,
 action text NOT NULL CHECK(length(action) BETWEEN 1 AND 60),
 subject_type text NOT NULL CHECK(subject_type IN ('user','background','admin','credit_grant')),
 subject_id text NOT NULL CHECK(length(subject_id) BETWEEN 1 AND 200),
 detail jsonb NOT NULL DEFAULT '{}',
 created_at timestamptz NOT NULL DEFAULT now()
);
-- statement
CREATE INDEX admin_audit_log_recent ON admin_audit_log(created_at DESC, id DESC);
-- statement
-- Admin'in düzenleyebildiği bir denetim günlüğü denetim günlüğü değildir:
-- tablo yalnızca eklemeye açık.
CREATE FUNCTION public.admin_audit_append_only() RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN RAISE EXCEPTION 'admin audit log is append-only'; END $$;
-- statement
CREATE TRIGGER admin_audit_append_only BEFORE UPDATE OR DELETE ON admin_audit_log
 FOR EACH ROW EXECUTE FUNCTION public.admin_audit_append_only();
-- statement
-- Kredi kaydı da değişmez kanıt: yalnız `used`, `revoked_at` ve hesap silmedeki
-- `user_id → NULL` serbest. Miktar, sebep, veren ve süre sonradan değiştirilemez.
CREATE OR REPLACE FUNCTION public.billing_immutable_snapshot() RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN
 IF TG_TABLE_NAME='plan_versions' THEN
  IF (to_jsonb(new)-'retired_at') IS DISTINCT FROM (to_jsonb(old)-'retired_at') THEN RAISE EXCEPTION 'plan version is immutable'; END IF;
 ELSIF TG_TABLE_NAME='billing_transactions' THEN
  IF (to_jsonb(new)-'user_id'-'invoice_reference') IS DISTINCT FROM (to_jsonb(old)-'user_id'-'invoice_reference')
   OR (new.user_id IS DISTINCT FROM old.user_id AND new.user_id IS NOT NULL)
   OR (old.invoice_reference IS NOT NULL AND new.invoice_reference IS DISTINCT FROM old.invoice_reference)
  THEN RAISE EXCEPTION 'financial transaction is immutable'; END IF;
 ELSIF TG_TABLE_NAME='subscription_periods' THEN
  IF (to_jsonb(new)-'status'-'closed_at'-'used_this_period'-'user_id') IS DISTINCT FROM (to_jsonb(old)-'status'-'closed_at'-'used_this_period'-'user_id')
   OR (new.user_id IS DISTINCT FROM old.user_id AND new.user_id IS NOT NULL)
  THEN RAISE EXCEPTION 'subscription period is immutable'; END IF;
 ELSIF TG_TABLE_NAME='credit_grants' THEN
  -- `user_id` ve `granted_by` yalnız NULL YÖNÜNE serbest: ikisi de
  -- `auth.users`'a `ON DELETE SET NULL` ile bağlı, yani hesap silindiğinde
  -- Postgres bu sütunları kendisi boşaltıyor. Bunu yasaklamak, kredi vermiş
  -- bir yöneticinin hesabının silinmesini kalıcı olarak imkânsız kılardı.
  -- Kimin verdiği bilgisi zaten `admin_audit_log.actor_id`'de duruyor ve o
  -- sütunun FK'si YOK — denetim izi silmeden etkilenmiyor.
  IF (to_jsonb(new)-'used'-'revoked_at'-'user_id'-'granted_by') IS DISTINCT FROM (to_jsonb(old)-'used'-'revoked_at'-'user_id'-'granted_by')
   OR (new.user_id IS DISTINCT FROM old.user_id AND new.user_id IS NOT NULL)
   OR (new.granted_by IS DISTINCT FROM old.granted_by AND new.granted_by IS NOT NULL)
  THEN RAISE EXCEPTION 'credit grant is immutable'; END IF;
 ELSIF TG_TABLE_NAME='user_consents' THEN
  IF (to_jsonb(new)-'user_id') IS DISTINCT FROM (to_jsonb(old)-'user_id')
   OR (new.user_id IS DISTINCT FROM old.user_id AND new.user_id IS NOT NULL)
  THEN RAISE EXCEPTION 'consent is immutable'; END IF;
 END IF;
 RETURN new;
END $$;
-- statement
CREATE TRIGGER credit_grant_snapshot BEFORE UPDATE ON credit_grants FOR EACH ROW EXECUTE FUNCTION public.billing_immutable_snapshot();
-- statement
-- RLS'siz tablo oluşturulmaz (kök CLAUDE.md kural 7): `anon` anahtarı herkese
-- açık, tabloyu koruyan tek şey RLS ve grant'lerin alınmış olması.
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['credit_grants','admin_audit_log'] LOOP
 EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated',t);
 END LOOP;
 REVOKE ALL ON SEQUENCE public.admin_audit_log_id_seq FROM anon, authenticated;
 REVOKE ALL ON FUNCTION public.admin_audit_append_only() FROM PUBLIC, anon, authenticated;
END $$;
